BOARD_TAG   = nano
BOARD_SUB   = atmega328
ARDUINO_DIR = /opt/arduino
MONITOR_PORT = /dev/ttyUSB1

AVRDUDE      = /opt/arduino/hardware/tools/avr/bin/avrdude
AVRDUDE_CONF = /opt/arduino/hardware/tools/avr/etc/avrdude.conf

AVR_TOOLS_PATH = $(ARDUINO_DIR)/hardware/tools/avr/bin
ARDUINO_LIBS = SerialDXL


include /opt/arduino-mk/Arduino.mk