# Makefile for plain AVR C file

NO_CORE = Yes

MCU = atmega2560
F_CPU = 16000000L

BOARD_TAG    = mega
BOARD_SUB    = atmega2560
AVRDUDE_ARD_PROGRAMMER = wiring
AVRDUDE_ARD_BAUDRATE = 115200

MONITOR_PORT = /dev/ttyACM0
ARDMK_DIR = /opt/arduino-mk
ARDUINO_DIR  = /opt/arduino

include $(ARDMK_DIR)/Arduino.mk
